# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_phylo2vec_wrappers", use_symbols = TRUE, package_name = "phylo2vec")

#' @usage NULL
#' @useDynLib phylo2vec, .registration = TRUE
NULL

#' Add a leaf to a Phylo2Vec vector
#' @export
add_leaf <- function(vector, leaf, branch) .Call(wrap__add_leaf, vector, leaf, branch)

#' Validate a Phylo2Vec vector
#' @export
check_m <- function(vector) invisible(.Call(wrap__check_m, vector))

#' Validate a Phylo2Vec vector
#' @export
check_v <- function(vector) invisible(.Call(wrap__check_v, vector))

#' Get the cophenetic distance matrix of a Phylo2Vec matrix
#' @export
cophenetic_from_matrix <- function(matrix) .Call(wrap__cophenetic_from_matrix, matrix)

#' Get the topological cophenetic distance matrix of a Phylo2Vec vector
#' @export
cophenetic_from_vector <- function(vector) .Call(wrap__cophenetic_from_vector, vector)

#' Convert an ancestry matrix to a Phylo2Vec vector
#' @export
from_ancestry <- function(matrix) .Call(wrap__from_ancestry, matrix)

#' Convert an edge list to a Phylo2Vec vector
#' @export
from_edges <- function(edges) .Call(wrap__from_edges, edges)

#' Convert a pairs matrix to a Phylo2Vec vector
#' @export
from_pairs <- function(pairs) .Call(wrap__from_pairs, pairs)

#' Check if a newick string has branch lengths
#' @export
has_branch_lengths <- function(newick) .Call(wrap__has_branch_lengths, newick)

#' Remove a leaf from a Phylo2Vec vector
#' @export
remove_leaf <- function(vector, leaf) .Call(wrap__remove_leaf, vector, leaf)

#' Sample a random tree with branch lengths via Phylo2Vec
#' @export
sample_matrix <- function(n_leaves, ordered) .Call(wrap__sample_matrix, n_leaves, ordered)

#' Sample a random tree topoloy via Phylo2Vec
#' @export
sample_vector <- function(n_leaves, ordered) .Call(wrap__sample_vector, n_leaves, ordered)

#' Get the ancestry matrix of a Phylo2Vec vector
#' @export
to_ancestry <- function(vector) .Call(wrap__to_ancestry, vector)

#' Get the edge list of a Phylo2Vec vector
#' @export
to_edges <- function(vector) .Call(wrap__to_edges, vector)

#' Recover a rooted tree (in Newick format) from a Phylo2Vec matrix
#' @export
to_newick_from_matrix <- function(matrix) .Call(wrap__to_newick_from_matrix, matrix)

#' Recover a rooted tree (in Newick format) from a Phylo2Vec vector
#' @export
to_newick_from_vector <- function(vector) .Call(wrap__to_newick_from_vector, vector)

#' Get pairs from a Phylo2Vec vector
#' @export
to_pairs <- function(vector) .Call(wrap__to_pairs, vector)

#' Convert a newick string to a Phylo2Vec vector
#' @export
to_matrix <- function(newick) .Call(wrap__to_matrix, newick)

#' Convert a newick string to a Phylo2Vec vector
#' @export
to_vector <- function(newick) .Call(wrap__to_vector, newick)


# nolint end
