# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_phylo2vec_wrappers", use_symbols = TRUE, package_name = "phylo2vec")

#' @usage NULL
#' @useDynLib phylo2vec, .registration = TRUE
NULL

#' Add a leaf to a Phylo2Vec vector
#' @export
add_leaf <- function(vector, leaf, branch) .Call(wrap__add_leaf, vector, leaf, branch)

#' Apply an integer-taxon label mapping (label_mapping)
#' to an integer-based newick (where leaves are integers)
#' and produce a mapped Newick (where leaves are strings (taxa))
#'
#' For more details, see `create_label_mapping`.
#'
#' Note 1: this does not check for the validity of the Newick string.
#'
#' Note 2: the parent nodes are removed from the output,
#' but the branch lengths/annotations are kept.
#' @export
apply_label_mapping <- function(newick, label_mapping_list) .Call(wrap__apply_label_mapping, newick, label_mapping_list)

#' Validate a Phylo2Vec vector
#' @export
check_m <- function(vector) invisible(.Call(wrap__check_m, vector))

#' Validate a Phylo2Vec vector
#' @export
check_v <- function(vector) invisible(.Call(wrap__check_v, vector))

#' Get the cophenetic distance matrix of a Phylo2Vec matrix
#' @export
cophenetic_from_matrix <- function(matrix) .Call(wrap__cophenetic_from_matrix, matrix)

#' Get the topological cophenetic distance matrix of a Phylo2Vec vector
#' @export
cophenetic_from_vector <- function(vector) .Call(wrap__cophenetic_from_vector, vector)

#' Create an integer-taxon label mapping (label_mapping)
#' from a string-based newick (where leaves are strings)
#' and produce a mapped integer-based newick (where leaves are integers).
#'
#' Note 1: this does not check for the validity of the Newick string.
#'
#' Note 2: the parent nodes are removed from the output,
#' but the branch lengths/annotations are kept.
#' @export
create_label_mapping <- function(newick) .Call(wrap__create_label_mapping, newick)

#' Convert an ancestry matrix to a Phylo2Vec vector
#' @export
from_ancestry <- function(matrix) .Call(wrap__from_ancestry, matrix)

#' Convert an edge list to a Phylo2Vec vector
#' @export
from_edges <- function(edges) .Call(wrap__from_edges, edges)

#' Convert a pairs matrix to a Phylo2Vec vector
#' @export
from_pairs <- function(pairs) .Call(wrap__from_pairs, pairs)

#' @export
get_common_ancestor <- function(vector, node1, node2) .Call(wrap__get_common_ancestor, vector, node1, node2)

#' Check if a newick string has branch lengths
#' @export
has_branch_lengths <- function(newick) .Call(wrap__has_branch_lengths, newick)

#' Produce an ordered version (i.e., birth-death process version)
#' of a Phylo2Vec vector using the Queue Shuffle algorithm.
#'
#' Queue Shuffle ensures that the output tree is ordered,
#' while also ensuring a smooth path through the space of orderings
#'
#' for more details, see https://doi.org/10.1093/gbe/evad213
#'
#' @param vector A Phylo2Vec vector (i.e., a vector of integers)
#' @param shuffle_cherries If true, the algorithm will shuffle cherries (i.e., pairs of leaves)
#' @return A list with two elements:
#' - `v`: The ordered Phylo2Vec vector
#' - `mapping`: A mapping of the original labels to the new labels
#' @export
queue_shuffle <- function(vector, shuffle_cherries) .Call(wrap__queue_shuffle, vector, shuffle_cherries)

#' Remove a leaf from a Phylo2Vec vector
#' @export
remove_leaf <- function(vector, leaf) .Call(wrap__remove_leaf, vector, leaf)

#' Sample a random tree with branch lengths via Phylo2Vec
#' @export
sample_matrix <- function(n_leaves, ordered) .Call(wrap__sample_matrix, n_leaves, ordered)

#' Sample a random tree topology via Phylo2Vec
#' @export
sample_vector <- function(n_leaves, ordered) .Call(wrap__sample_vector, n_leaves, ordered)

#' Get the ancestry matrix of a Phylo2Vec vector
#' @export
to_ancestry <- function(vector) .Call(wrap__to_ancestry, vector)

#' Get the edge list of a Phylo2Vec vector
#' @export
to_edges <- function(vector) .Call(wrap__to_edges, vector)

#' Recover a rooted tree (in Newick format) from a Phylo2Vec matrix
#' @export
to_newick_from_matrix <- function(matrix) .Call(wrap__to_newick_from_matrix, matrix)

#' Recover a rooted tree (in Newick format) from a Phylo2Vec vector
#' @export
to_newick_from_vector <- function(vector) .Call(wrap__to_newick_from_vector, vector)

#' Get pairs from a Phylo2Vec vector
#' @export
to_pairs <- function(vector) .Call(wrap__to_pairs, vector)

#' Convert a newick string to a Phylo2Vec vector
#' @export
to_matrix <- function(newick) .Call(wrap__to_matrix, newick)

#' Convert a newick string to a Phylo2Vec vector
#' @export
to_vector <- function(newick) .Call(wrap__to_vector, newick)


# nolint end
