# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_phylo2vec_wrappers", use_symbols = TRUE, package_name = "phylo2vec")

#' @usage NULL
#' @useDynLib phylo2vec, .registration = TRUE
NULL

#' Sample a random tree via Phylo2Vec
#' @export
sample_vector <- function(n_leaves, ordered) .Call(wrap__sample_vector, n_leaves, ordered)

#' Add a leaf to a Phylo2Vec vector
#' @export
add_leaf <- function(vector, leaf, branch) .Call(wrap__add_leaf, vector, leaf, branch)

#' Get the topological cophenetic distance matrix of a Phylo2Vec vector
#' @export
cophenetic_distances <- function(vector) .Call(wrap__cophenetic_distances, vector)

#' Convert an edge list to a Phylo2Vec vector
#' @export
from_edges <- function(edges) .Call(wrap__from_edges, edges)

#' Convert an ancestry matrix to a Phylo2Vec vector
#' @export
from_ancestry <- function(matrix) .Call(wrap__from_ancestry, matrix)

#' Remove a leaf from a Phylo2Vec vector
#' @export
remove_leaf <- function(vector, leaf) .Call(wrap__remove_leaf, vector, leaf)

#' Get the ancestry matrix of a Phylo2Vec vector
#' @export
to_ancestry <- function(vector) .Call(wrap__to_ancestry, vector)

#' Get the edge list of a Phylo2Vec vector
#' @export
to_edges <- function(vector) .Call(wrap__to_edges, vector)

#' Recover a rooted tree (in Newick format) from a Phylo2Vec vector
#' @export
to_newick_from_vector <- function(vector) .Call(wrap__to_newick_from_vector, vector)

#' Recover a rooted tree (in Newick format) from a Phylo2Vec matrix
#' @export
to_newick_from_matrix <- function(matrix) .Call(wrap__to_newick_from_matrix, matrix)

#' Convert a newick string to a Phylo2Vec vector
#' @export
to_vector <- function(newick) .Call(wrap__to_vector, newick)

#' Validate a Phylo2Vec vector
#' @export
check_v <- function(vector) invisible(.Call(wrap__check_v, vector))


# nolint end
