name: CI Rust

on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          # Commenting out the following lines will enable the beta and nightly builds
          # currently not in use since we can't format the code with the beta and nightly builds
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v5
      - name: Setup Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Run linter
        run: cargo fmt --check
      - name: Compile Code
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
